<?php

/**
 * @file
 * Contains commerce_multistore.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\commerce_multistore\MultistoreAccessControlHandler;

/**
 * Implements hook_help().
 */
function commerce_multistore_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_multistore module.
    case 'help.page.commerce_multistore':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Implements multiple stores/store owners model.') . '</p>';

      return $output;

    default:
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function commerce_multistore_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['commerce_store']->setAccessClass(MultistoreAccessControlHandler::class);
}
